VAGRANTFILE_API_VERSION = "2"
Vagrant.require_version ">= 1.7.2"
NICS=["wlp3s0","enp3s0","wlp54s0","enp53s0"]

Vagrant.configure(2) do |config|
  config.vm.box = 'bento/centos-7.4'
  config.vm.box_check_update = false
  config.vm.hostname = "pxe"
  config.vm.network "public_network", bridge: NICS, ip: "192.168.10.215"
  config.vm.provision :shell, :path => 'pxe.sh'



  config.vm.provider "virtualbox" do |vb|
     #   vb.gui = true
     vb.memory = "2048"
     vb.cpus = 1
     vb.name = "PXE"
  end

end
