#!/bin/bash

JENKINSPOD=$(kubectl get pods -n services | grep jenkins | awk '{print $1}')

kubectl exec -i -n services $JENKINSPOD -- /usr/local/bin/install-plugins.sh < jenkins-plugins.txt

#kubectl exec -i -n services $JENKINSPOD -- sh -c 'cp /usr/share/jenkins/ref/plugins/* /var/jenkins_home/plugins'

#kubectl exec -i -n services $JENKINSPOD -- sh -c 'kill -1 `ls /proc | grep "^[0-9][0-9]*$"`'
