apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: services
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30005
  selector:
    app: registry

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-jnlp
spec:
  type: ClusterIP
  ports:
    - port: 50000
      targetPort: 50000
  selector:
    app: jenkins
