apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv
  labels:
    type: local
  namespace: services
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/k8s/data"
