#Vagrant::Config.run do | config |
Vagrant.configure(2) do | config |
  config.vm.box = "bento/centos-7.4"

  config.vm.define :mark do | mark |
    config.vm.provider "virtualbox" do | vb |
      vb.memory = 2048
      vb.name = "Marking"
    end
    mark.vm.host_name = "marking"
    mark.vm.provision :shell, :path => 'marking.sh'
    mark.vm.network "forwarded_port", guest: 80, host: 1080, protocol: 'tcp'
    mark.vm.network "forwarded_port", guest: 5432, host: 5432, protocol: 'tcp'
  end
end
