# Set the following variable values to your network and computer
YOURSUBNET="192.168.10"
NICS=["wlp3s0","enp3s0","wlp54s0","enp53s0"]


Vagrant.configure(2) do | config |

  # Private Docker reg
  config.vm.define :dockerreg do | dockerreg |
    dockerreg.vm.provider "virtualbox" do | vb |
      vb.memory = 1024
      vb.name = "Docker Registry"
      vb.cpus = 1
    end
    dockerreg.vm.network "public_network", bridge: NICS, type: "dhcp"
    dockerreg.vm.host_name = "dockerreg"
    dockerreg.vm.network "private_network", ip: "192.168.56.82"
    dockerreg.vm.provision :shell, :path => 'bin/allnodes.sh'
    dockerreg.vm.provision :shell, :path => 'bin/dockerreg.sh'
  end

  # K8s Worker nodes
  (1..2).each do |instance|
    config.vm.define "worker#{instance}" do | worker |
      worker.vm.provider "virtualbox" do | vb |
        vb.memory = 2048
        vb.name = "K8s Worker #{instance}"
        vb.cpus = 1
      end
      # worker.vm.network "public_network", bridge: NICS, type: "dhcp"
      worker.vm.host_name = "worker#{instance}"
      worker.vm.network "private_network", ip: "192.168.56."+"7#{instance}"
      worker.vm.provision :shell, :path => 'bin/allnodes.sh'
    end
  end

  # K8s Control plane
  config.vm.define :controller do | cp |
    cp.vm.provider "virtualbox" do | vb |
      vb.memory = 2048
      vb.name = "K8s Control Plane"
      vb.cpus = 1
    end
    cp.vm.network "public_network", bridge: NICS, type: "dhcp"
    cp.vm.host_name = "k8scontroller"
    cp.vm.network "private_network", ip: "192.168.56.70"
    cp.vm.provision :shell, :path => 'bin/allnodes.sh'
    cp.vm.provision :shell, :path => 'bin/controlplane.sh'
  end

  # Kubernetes UI Controller
  config.vm.define :rui do | rui |
    rui.vm.provider "virtualbox" do | vb |
      vb.memory = 2048
      vb.name = "rancherui"
      vb.cpus = 1
    end
    rui.vm.host_name = "rui.localdomain"
    rui.vm.network "public_network", bridge: NICS, type: "dhcp"
    rui.vm.network "private_network", ip: "192.168.56.80"
    rui.vm.provision :shell, :path => 'bin/allnodes.sh'
    rui.vm.provision :shell, :path => 'bin/rancherui.sh'
  end

  # Load balancer external
  config.vm.define :proxy do | proxy |
    proxy.vm.provider "virtualbox" do | vb |
      vb.memory = 1024
      vb.name = "RKE Proxy"
      vb.cpus = 1
    end
    proxy.vm.host_name = "proxy.localdomain"
    proxy.vm.network "public_network", bridge: NICS, type: "dhcp"
    proxy.vm.network "private_network", ip: "192.168.56.81"
    proxy.vm.provision :shell, :path => 'bin/proxy.sh'
  end

  # Defaults
  config.vm.box = "bento/ubuntu-22.04"
  #config.vm.box = "almalinux/8"
  config.ssh.username = "vagrant"
  #config.ssh.password = "vagrant"

end
