VAGRANTFILE_API_VERSION = "2"
Vagrant.require_version ">= 1.7.2"

Vagrant.configure(2) do |config|
  config.vm.box = 'bento/centos-7.4'
  config.vm.box_check_update = false
  config.vm.hostname = "dns.training.local"
  config.vm.network "public_network", ip: "192.168.10.21"
  config.vm.provision :shell, :path => 'dns.sh'



  config.vm.provider "virtualbox" do |vb|
     #   vb.gui = true
     vb.memory = "512"
     vb.cpus = 1
     vb.name = "DNS"
  end

end
