apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: services
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
    - "--dockerfile=$DOCKERFILE"
    - "--context=dir://$BUILDDIR"
    - "--destination=registry.services/$PROJECTNAME/$IMAGE:$TAG"
    env:
    - name: PROJECTNAME
      value: monitoring
    - name: IMAGE
      value: none
    - name: TAG
      value: 0.0
    - name: DOCKERFILE
      value: Dockerfile
    - name: BUILDDIR
      value: .
  restartPolicy: Never
