Vagrant.configure("2") do |config|

  # Ubuntu 64bit unity - client
  config.vm.define :ubuntu do | ubuntu |
    config.vm.provider "virtualbox" do | vb |
      vb.memory = 512
      vb.name = "Ansible Ubuntu"
      #vb.gui = true
    end
    ubuntu.vm.host_name = "ubuntu.al.local"
    ubuntu.vm.box = "ubuntu/trusty64"
    ubuntu.vm.network "private_network", ip: "10.0.0.4"
  end

  # CentOS CLI -client
  config.vm.define :rhel do | rhel |
    config.vm.provider "virtualbox" do | vb |
      vb.memory = 512
      vb.name = "Ansible RHEL"
    end
    rhel.vm.host_name = "rhel.al.local"
    rhel.vm.box = "bento/centos-7.2"
    rhel.vm.network "private_network", ip: "10.0.0.3"
    rhel.vm.provision :shell, :path => 'bin/ansible.sh'
  end

  # CentOS Ansible Provisioner
  config.vm.define :ap do | ap |
    config.vm.provider "virtualbox" do | vb |
      vb.memory = 1024
      vb.name = "Ansible Prov"
    end
    ap.vm.host_name = "ap.al.local"
    ap.vm.box = "bento/centos-7.2"
    ap.vm.network "private_network", ip: "10.0.0.2"
    ap.vm.provision :shell, path: "bin/ansible.sh"
  end
end
