apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb-status
  labels:
    app: lbstatus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lbstatus
  template:
    metadata:
      labels:
        app: lbstatus
    spec:
      containers:
        - name: lb-status
          image: hashicorp/http-echo
          args:
            - "-text=ok"
          ports:
            - containerPort: 5678

---

kind: Service
apiVersion: v1
metadata:
  name: lb-status-service
spec:
  selector:
    app: lbstatus
  ports:
    - port: 80
      targetPort: 5678 # Default port for image

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lbstatus-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: status.k8s.tps.local
    http:
      paths:
        - path: /
          backend:
            serviceName: lb-status-service
            servicePort: 80
