#!/bin/bash
# OpenShift control script
# chkconfig: 35 99 99
# description: Openshift service control

echo "Detecting NIC"
if ! ifconfig enp0s3 >/dev/null 2>&1
then
  if ifconfig eth0 | grep 10.0.2.15 >/dev/null 2>&1
  then
    # This is vagrant so use eth1
    nicname=eth1
  else
    nicname=eth0
  fi
else
  nicname=enp0s3
fi

function start {
  echo "Starting OpenShift"
  writeConfig=$1
  # Check if oc cluster has already been launched
  #PublicIP=$(ifconfig | grep -A3 docker0 | grep inet | awk '{print $2}')
  echo "Detecting external Hostname"
  PublicIP=$(cat /srvname)
  PrivateIP=$(ifconfig | grep -A3 ${nicname} | grep inet | awk '{print $2}')
  export PublicIP PrivateIP

  echo "Starting cluster"
  oc cluster up --public-hostname="$PublicIP" --base-dir=/openshift --write-config=${writeConfig} --skip-registry-check=true
}

case $1 in
  'clean')
    echo "Removing old environment"
    oc cluster down
    for x in $(sudo mount | grep openshift | awk '{print $3}')
    do
      sudo umount $x
    done
    docker rm -f $(docker ps -a | awk '{print $1}' | tail -n +2)
    rm -rf /openshift
    echo "Creating new configuration"
    start "true"
    # We have to start once
    echo "Starting initial cluster to get configuration"
    start "false"
    echo "Stopping cluster to write external IP for web console"
    oc cluster down
    # Change the IP in the
    echo "Writing the web console IP to configuration"
    sed -i "s/server: https://127\.0\.0\.1/server: ${PublicIP}/" /openshift/openshift-controller-manager/openshift-master.kubeconfig
    echo "Starting official system"
    start "false"
    ;;

  'start')
    start "false"
    ;;

  'stop')
    oc cluster down
    ;;

  'status')
    docker ps
    ;;
  'restart')
    oc cluster down
    sleep 30
    start
esac
