Vagrant.configure(2) do | config |

  # Kubernetes Master
  config.vm.define :master do | master |
    master.vm.provider "virtualbox" do | vb |
      vb.memory = 8192
      vb.name = "RKE Master"
      vb.cpus = 2
    end
    master.vm.host_name = "master.localdomain"
    master.vm.network "public_network", bridge: "wlp3s0"
    master.vm.network "private_network", ip: "10.0.0.10"
    master.vm.provision :shell, :path => 'bin/master.sh'
  end

  # Defaults
  config.vm.box = "ubuntu/groovy64"
  config.ssh.username = "vagrant"
  #config.ssh.password = "vagrant"

end
