#!/bin/bash

# This script validates your Vagrant config
# Created by: Steve Shilling
# Created: 10th Jan 2018

output=$(vagrant status 2>&1)
#if vagrant status >/dev/null 2>&1
if echo "$output" | grep "Current machine states" >/dev/null
then
  echo "Validation OK"
else
  echo "That's not good you have an error" 1>&2
  #vagrant status
  echo "$output"
fi
