Vagrant.configure(2) do | config |

  # Jira basic install
  config.vm.define :jira do | jira |
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      #vb.cpus = 1
      vb.name = "Jira"
    end
    jira.vm.host_name = "jira"
    #jira.vm.box     = "CentOS7.0_x86_64_minimal.box"
    jira.vm.provision :shell, :path => 'select.sh'
    jira.vm.network "forwarded_port", guest: 8080, host: 1080, protocol: 'tcp'
  end

  # Defaults
  #config.vm.box = "bento/centos-7.2"
  config.vm.box = "almalinux/8"
  config.ssh.username = "vagrant"
end
