#!/bin/bash

. bin/config

if [ ! -e tmpconfig ]
then
  echo "No configuration file called tmpconfig"
  echo "Cannot stop the machines"
  exit 1
fi

for machine in $hostlist
do
  if VBoxManage list runningvms | grep $machine
  then
    echo "Shutting down $machine"
    sshpass -p $VMPASS ssh root@$(grep "^export $machine" tmpconfig | awk -F= '{print $2}') 'init 0'
  else
    echo "$machine has already stopped"
  fi
done

vagrant halt proxy
