# Set the following variable values to your network and computer
YOURSUBNET="192.168.10"
NICS=["wlp3s0","enp3s0","wlp54s0","enp53s0"]


Vagrant.configure(2) do | config |

  # Worker nodes
  config.vm.define :node1 do | node1 |
    node1.vm.provider "virtualbox" do | vb |
      vb.memory = 4096
      vb.name = "K8s Node1"
      vb.cpus = 2
    end
    node1.vm.host_name = "node1.localdomain"
    node1.vm.network "public_network", bridge: NICS, ip: YOURSUBNET+".61"
    node1.vm.network "private_network", ip: "10.0.0.11"
    node1.vm.provision "shell", path: "bin/node.sh"
  end

  config.vm.define :node2 do | node2 |
    node2.vm.provider "virtualbox" do | vb |
      vb.memory = 4096
      vb.name = "K8s Node2"
      vb.cpus = 2
    end
    node2.vm.host_name = "node2.localdomain"
    node2.vm.network "public_network", bridge: NICS, ip: YOURSUBNET+".62"
    node2.vm.network "private_network", ip: "10.0.0.12"
    node2.vm.provision "shell", path: "bin/node.sh"
  end

  # Kubernetes Master
  config.vm.define :master do | master |
    master.vm.provider "virtualbox" do | vb |
      vb.memory = 4096
      vb.name = "K8s Master"
      vb.cpus = 1
    end
    master.vm.host_name = "master.localdomain"
    master.vm.network "public_network", bridge: NICS, ip: YOURSUBNET+".60"
    master.vm.network "private_network", ip: "10.0.0.10"
    master.vm.provision "shell", path: "bin/node.sh"
  end

  # # Load balancer external
  # config.vm.define :proxy do | proxy |
  #   proxy.vm.provider "virtualbox" do | vb |
  #     vb.memory = 1024
  #     vb.name = "K8s Proxy"
  #     vb.cpus = 1
  #   end
  #   proxy.vm.host_name = "proxy.localdomain"
  #   proxy.vm.network "public_network", bridge: NICS, ip: YOURSUBNET+".65"
  #   proxy.vm.network "private_network", ip: "10.0.0.15"
  #   proxy.vm.provision :shell, :path => 'bin/proxy.sh'
  # end

  # Defaults
  #config.vm.box = "ubuntu/groovy64"
  #config.vm.box = "almalinux/8"
  config.vm.box = "bento/centos-7.4"
  config.ssh.username = "vagrant"
  #config.ssh.password = "vagrant"

end
