#!/bin/bash

. src/config
.
echo "Select host to log on to:"
select host in rkenode1 rkenode2 rkemaster proxy
do
  if [[ $host == proxy ]]
  then
    vagrant ssh proxy
  else
    sshpass -p $VMPASS ssh $SSHOPTS root@$(grep "^export $host" tmpconfig | awk -F= '{print $2}')
  fi
done
