#!/bin/bash

# Script to remove the VMs from the environment

for machine in rkenode1 rkenode2 rkemaster
do
  if ! VBoxManage list vms | grep $machine
  then
    continue
  fi
  VBoxManage controlvm $machine poweroff
  VBoxManage unregistervm $machine --delete
done

rm tmpconfig etc_hosts

vagrant destroy -f proxy
