#!/bin/bash

. src/config

for machine in rkenode1 rkenode2 rkemaster
do
  if ! VBoxManage list runningvms | grep $machine
  then
    echo "Starting $machine"
    VBoxManage startvm $machine
  else
    echo "$machine is already running"
  fi
done

vagrant up proxy
