Vagrant.configure(2) do | config |

  # Worker nodes
  config.vm.define :node1 do | node1 |
    node1.vm.provider "virtualbox" do | vb |
      vb.memory = 4096
      vb.name = "RKE Node1"
      vb.cpus = 2
    end
    node1.vm.host_name = "node1.localdomain"
    node1.vm.network "public_network", bridge: "wlp3s0"
    node1.vm.network "private_network", ip: "10.0.0.11"
    node1.vm.provision :shell, :path => 'bin/node.sh'
  end

  config.vm.define :node2 do | node2 |
    node2.vm.provider "virtualbox" do | vb |
      vb.memory = 4096
      vb.name = "RKE Node2"
      vb.cpus = 2
    end
    node2.vm.host_name = "master.localdomain"
    node2.vm.network "public_network", bridge: "wlp3s0"
    node2.vm.network "private_network", ip: "10.0.0.12"
    node2.vm.provision :shell, :path => 'bin/node.sh'
  end

  # Kubernetes Master
  config.vm.define :master do | master |
    master.vm.provider "virtualbox" do | vb |
      vb.memory = 4096
      vb.name = "RKE Master"
      vb.cpus = 1
    end
    master.vm.host_name = "master.localdomain"
    master.vm.network "public_network", bridge: "wlp3s0"
    master.vm.network "private_network", ip: "10.0.0.10"
    master.vm.provision :shell, :path => 'bin/master.sh'
  end

  # Defaults
  config.vm.box = "ubuntu/groovy64"
  config.ssh.username = "vagrant"
  #config.ssh.password = "vagrant"

end
