# Set the following variable values to your network and computer
YOURSUBNET="192.168.10"
NICS=["wlp3s0","enp3s0","wlp54s0","enp53s0"]


Vagrant.configure(2) do | config |

  # Kubernetes UI Controller
  # config.vm.define :kui do | kui |
  #   kui.vm.provider "virtualbox" do | vb |
  #     vb.memory = 2048
  #     vb.name = "Rancher UI"
  #     vb.cpus = 1
  #   end
  #   kui.vm.host_name = "kui.localdomain"
  #   kui.vm.network "public_network", bridge: NICS, ip: YOURSUBNET+".63"
  #   kui.vm.network "private_network", ip: "10.0.0.13"
  #   kui.vm.provision :shell, :path => 'bin/node.sh'
  #   kui.vm.provision :shell, :path => 'bin/rancherui-master.sh'
  # end

  # Load balancer external
  config.vm.define :proxy do | proxy |
    proxy.vm.provider "virtualbox" do | vb |
      vb.memory = 1024
      vb.name = "RKE Proxy"
      vb.cpus = 1
    end
    proxy.vm.host_name = "proxy.localdomain"
    proxy.vm.network "public_network", bridge: NICS, ip: YOURSUBNET+".65"
    proxy.vm.provision :shell, :path => 'bin/proxy.sh'
    proxy.vm.box = "ubuntu/groovy64"
  end

  # Defaults
  #config.vm.box = "ubuntu/groovy64"
  config.vm.box = "almalinux/8"
  config.ssh.username = "vagrant"
  #config.ssh.password = "vagrant"

end
