#!/bin/bash

. src/config

if [ ! -e tmpconfig ]
then
  echo "No configuration file called tmpconfig"
  echo "Cannot stop the machines, or machines already destroyed"
  echo "Machines:"
  VBoxManage list vms | egrep 'rke'
  vagrant status
  exit 1
fi

for machine in rkenode1 rkenode2 rkemaster
do
  if VBoxManage list runningvms | grep $machine
  then
    echo "[RUNNING] $machine"
  elif VBoxManage list vms | grep $machine
  then
    echo "[STOPPED] $machine"
  else
    echo "[NOEXIST] $machine"
  fi
done

vagrant status
