VAGRANTFILE_API_VERSION = "2"
Vagrant.require_version ">= 1.7.2"

Vagrant.configure(2) do |config|
  config.vm.define :master do | master |
    config.vm.provider "virtualbox" do |vb|
       vb.memory = "8192"
       vb.cpus = 2
       vb.name = "OpenShift"
    end
    master.vm.hostname = "OpenShift"
    master.vm.network "public_network", ip: "192.168.10.23"
    master.vm.provision :shell, :path => 'openshift.sh'
  end

  config.vm.box = 'envimation/ubuntu-xenial-docker'
end
