NICS=["wlp3s0","enp3s0","wlp54s0","enp53s0"]

Vagrant.configure("2") do |config|
    config.vm.provider "virtualbox" do | vb |
        vb.memory = 4096
        vb.name = "OKDServices"
        vb.cpus = 2
    end
    config.vm.hostname = "okd4-services.okd.local"
    config.vm.network "public_network", bridge: NICS, ip: "192.168.10.210", auto_config: false
    config.vm.provision :shell, :path => 'provision/services.sh'
    config.vm.provision :shell, :path => 'provision/pxe.sh'
    config.vm.box = "fedora/37-cloud-base"
    config.vm.box_version = "37.20221105.0"
end
