NICS=["wlp3s0","enp3s0","wlp54s0","enp53s0"]
YOURSUBNET="192.168.10"

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do | v |
    v.memory = 10240
    v.cpus = 2
  end
  config.vm.network "public_network", bridge: NICS, ip: YOURSUBNET+".23"
  config.vm.box = "almalinux/8"
  config.vm.box_version = "8.4.20210527"
  config.vm.provision :shell, :path => 'openshift.sh'
end
